blogs/urls.py
from django.urls import path
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogs/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='Название')
    content = models.TextField(verbose_name='Содержание')
    image = models.ImageField(upload_to='images/',blank=True, verbose_name='Изображение')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    publication = models.BooleanField(default=True, verbose_name='Состояние публикации')
    views_count = models.IntegerField(default=0 ,verbose_name='Просмотры')

    def __str__(self):
        return f'{self.title} {"Опубликовано" if self.publication else "Не опубликовано"}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'
        ordering = ['-views_count',]

blogs/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy

from blogs.models import Blog


class BlogCreateView(CreateView):
    model = Blog
    fields = ['title', 'content', 'image']
    template_name = 'blog_form.html'
    success_url = reverse_lazy('blogs:blog_list')


class BlogListView(ListView):
    model = Blog
    template_name = 'blog_list.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return Blog.objects.filter(publication=True)


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blog_detail.html'
    context_object_name = 'blog'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        Blog.objects.filter(pk=obj.pk).update(views_count= obj.views_count + 1)
        return obj


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ['title', 'content', 'image', 'publication']
    template_name = 'blog_form.html'

    def get_success_url(self):
        return reverse_lazy('blogs:blog_detail', kwargs={'pk': self.object.pk})


class BlogDeleteView(DeleteView):
    model = Blog
    template_name = 'blog_confirm_delete.html'
    success_url = reverse_lazy('blogs:blog_list')

blogs/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skyblogs</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

{% include 'header.html'%}

{% block description%}
{% endblock%}

<div class="container">

{% block content%}
{% endblock%}

</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

blogs/templates/blog_confirm_delete.html
{% extends 'base.html'%}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skyblogs</h1>
    <p class="lead">Удаление блога</p>
</div>
{% endblock%}

{% block content%}
<p>Вы действительно хотите удалить '{{ blog.title }}'?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'blogs:blog_list' %}" class="btn btn-primary">Отменить</a>
</form>
{% endblock%}

blogs/templates/blog_detail.html
{% extends 'base.html'%}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skyblogs</h1>
</div>
{% endblock%}

{% block content%}
<h2 class="display-10">{{ blog.title }}</h2>
<p>Дата публикации: {{ blog.created_at }}</p>
<p>{{ blog.content }}</p>
<p>Количество просмотров: {{ blog.views_count }}</p>
<p>{% if blog.publication %} Опубликовано {% else %} Не опубликовано {% endif %}</p>
<a href="{% url 'blogs:blog_update' blog.pk %}" class="btn btn-secondary">Редактировать</a>
<a href="{% url 'blogs:blog_delete' blog.pk %}" class="btn btn-danger">Удалить</a>
<a href="{% url 'blogs:blog_list'%}" class="btn btn-primary">Вернуться назад</a>
{% endblock%}

blogs/templates/blog_form.html
{% extends 'base.html'%}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skyblogs</h1>
    <p class="lead">Создание/редактирование блога</p>
</div>
{% endblock%}

{% block content%}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'blogs:blog_list' %}" class="btn btn-primary">Отменить</a>
</form>
{% endblock%}

blogs/templates/blog_list.html
{% extends 'base.html'%}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skyblogs</h1>
    <p class="lead">Наши блоги</p>
</div>
{% endblock%}

{% block content%}
<ul class="list-group">
    {% for blog in blogs %}
        <li>
            <a href="{% url 'blogs:blog_detail' blog.pk %}">{{ blog.title }}</a> - {{ blog.views_count }}
        </li>
    {% endfor %}
</ul>
{% endblock%}

blogs/templates/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skyblogs</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'blogs:blog_list' %}">Блоги</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blogs:blog_create' %}">Добавить блог</a>
    </nav>
</div>