blogs/urls.py
from django.urls import path
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, UserDetailView, UserUpdateView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:catalog'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user_profile'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')

    first_name = models.CharField(max_length=35, verbose_name='Имя', blank=True, null=True, help_text='Введите имя')
    last_name = models.CharField(max_length=35, verbose_name='Фамилия', blank=True, null=True, help_text='Введите фамилию')
    phone = models.CharField(max_length=15, verbose_name='Телефон', blank=True, null=True, help_text='Введите номер телефона')
    avatar = models.ImageField(upload_to='avatars/',verbose_name='Аватар', blank=True, null=True, help_text='Загрузите фото профиля')
    country = models.CharField(max_length=35, verbose_name='Страна', blank=True, null=True, help_text='Ваша страна')

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    """Форма регистрации"""
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, ModelForm):
    """Форма для модели User"""
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'avatar', 'phone', 'country')

users/views.py
from django.core.mail import send_mail
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import DetailView

from users.forms import UserRegisterForm, UserForm
from users.models import User


class RegisterView(CreateView):
    template_name = 'users/user_form.html'
    form_class = UserRegisterForm
    success_url = reverse_lazy('catalog:catalog')

    def form_valid(self, form):
        user = form.save()
        self.send_welcome_email(user.email)
        return super().form_valid(form)

    def send_welcome_email(self, user_email):
        subject = 'Добро пожаловать в наш сервис'
        message = 'Спасибо, что зарегистрировались в нашем сервисе!'
        from_email = 'Testmail123987@yandex.ru'
        recipient_list = [user_email]
        send_mail(subject, message, from_email, recipient_list)


class UserDetailView(DetailView):
    model = User
    template_name = 'users/user_profile.html'
    context_object_name = 'user'


class UserUpdateView(UpdateView):
    model = User
    form_class = UserForm

    def get_success_url(self):
        return reverse_lazy('users:user_profile', kwargs={'pk': self.object.pk})

users/templates/users/user_form.html
{% extends 'catalog/base.html'%}
{% load my_tags %}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Регистрация</p>
</div>
{% endblock%}

{% block content%}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {% if user.is_authenticated %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    {% else %}
    <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
    {% endif %}
</form>
{% endblock%}

users/templates/users/user_profile.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="container">
    <h1 class="lead">{{ user.email }}</h1>
    <img src="{{ user.avatar | media_filter }}" style="width: 100px; height: 100px;" class="img-thumbnail rounded-circle">
    <p>Имя:{{ user.first_name }}</p>
    <p>Фамилия:{{ user.last_name }}</p>
    <p>Телефон:{{ user.phone }}</p>
    <p>Страна:{{ user.country }}</p>
    <a class="mb-2 btn btn-lg btn-block btn-outline-primary" href="{% url 'users:user_update' user.pk %}" role="button">Редактировать</a>
</div>
{% endblock %}