blogs/urls.py
from django.urls import path
from .views import BlogCreateView, BlogListView, BlogDetailView, BlogUpdateView, BlogDeleteView

app_name = 'blogs'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('create/', BlogCreateView.as_view(), name='blog_create'),
    path('<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('update/<int:pk>/', BlogUpdateView.as_view(), name='blog_update'),
    path('delete/<int:pk>/', BlogDeleteView.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from .views import CatalogListView, ProductDetailView, ContactsView, ProductCreateView, ProductUpdateView, \
    ProductDeleteView, ProductsByCategoryView

app_name = 'catalog'

urlpatterns = [
    path('', CatalogListView.as_view(), name='catalog'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('create/', ProductCreateView.as_view(), name='product_create'),
    path('update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
    path('category/<int:category>/', ProductsByCategoryView.as_view(), name='products_by_category'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogs.urls', namespace='blogs')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import RegisterView, UserDetailView, UserUpdateView

app_name = 'users'

urlpatterns = [
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', LogoutView.as_view(next_page='catalog:catalog'), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('users/<int:pk>/', UserDetailView.as_view(), name='user_profile'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
]

catalog/models.py
from django.db import models

from users.models import User


class Category(models.Model):
    """Модель для категорий товаров"""
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'
        ordering = ['name',]


class Product(models.Model):
    """Модель для товаров"""
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='images/', blank=True, verbose_name='Изображение')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='products')
    price = models.FloatField (verbose_name='Цена')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения')
    is_published = models.BooleanField(default=False, verbose_name='Статус публикации')
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='Владелец', null=True, blank=True)

    def __str__(self):
        return f'{self.name} {self.category} {self.price}'

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'
        ordering = ['name',]
        permissions = [
            ('can_unpublish_product', 'Может отменять публикацию продукта'),
        ]

catalog/forms.py
from django.core.exceptions import ValidationError
from django.forms import ModelForm, BooleanField

from catalog.models import Product


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = 'form-check-input'
            else:
                field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, ModelForm):
    """Форма для модели Product"""
    class Meta:
        model = Product
        exclude = ('created_at', 'updated_at', 'owner')

    forbidden_words = [
        'казино', 'криптовалюта', 'крипта', 'биржа',
        'дешево', 'бесплатно', 'обман', 'полиция', 'радар'
    ]

    def clean(self):
        """Валидация полей name и description на запрещенные слова"""
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        description = cleaned_data.get('description')

        forbidden_words_in_name = []
        forbidden_words_in_description = []

        for word in self.forbidden_words:
            if word in name.lower():
                forbidden_words_in_name.append(word)

        for word in self.forbidden_words:
            if word in description.lower():
                forbidden_words_in_description.append(word)

        if forbidden_words_in_name and forbidden_words_in_description:
            raise ValidationError(f'В названии и описании есть запрещенные слова: {", ".join(forbidden_words_in_name)}, {", ".join(forbidden_words_in_description)}')
        elif forbidden_words_in_name:
            raise ValidationError(f'В названии есть запрещенные слова: {", ".join(forbidden_words_in_name)}')
        elif forbidden_words_in_description:
            raise ValidationError(f'В описании есть запрещенные слова: {", ".join(forbidden_words_in_description)}')

        return cleaned_data


    def clean_price(self):
        """Валидация поля price на отрицательное значение"""
        price = self.cleaned_data['price']

        if price <= 0:
            raise ValidationError('Цена продукта не может быть нулевой или отрицательной.')

        return price

catalog/views.py
from django.http import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.utils.decorators import method_decorator

from catalog.forms import ProductForm
from catalog.models import Product, Category
from catalog.services import products_by_category


class CategoriesMixin:

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context


class ProductsByCategoryView(CategoriesMixin, ListView):
    template_name = 'catalog/products_by_category.html'
    context_object_name = 'products_by_category'

    def get_queryset(self):
        """Получаем товары по категории"""
        category = self.kwargs.get('category')
        return products_by_category(category)

    def get_context_data(self, **kwargs):
        """Добавляем категорию в контекст"""
        context = super().get_context_data(**kwargs)
        category = self.kwargs.get('category')

        context['category'] = get_object_or_404(Category, id=category)

        return context


class ProductCreateView(LoginRequiredMixin, CategoriesMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, PermissionRequiredMixin, CategoriesMixin, UpdateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:catalog')
    permission_required = 'catalog:can_unpublish_product'

    def has_permission(self):
        product = self.get_object()
        user = self.request.user

        if product.owner == user:
            return True

        return super().has_permission()


class CatalogListView(CategoriesMixin, ListView):
    model = Product
    template_name = 'catalog/catalog.html'
    context_object_name = 'products'

    def get_queryset(self):
        queryset = cache.get('catalog_cache')
        if not queryset:
            queryset = super().get_queryset()
            cache.set('catalog_cache', queryset, 60 * 15)
        return queryset


@method_decorator(cache_page(60 * 15), name='dispatch')
class ProductDetailView(CategoriesMixin, DetailView):
    model = Product
    template_name = 'catalog/product_detail.html'
    context_object_name = 'product'


class ProductDeleteView(LoginRequiredMixin, PermissionRequiredMixin, CategoriesMixin, DeleteView):
    model = Product
    template_name = 'catalog/product_confirm_delete.html'
    success_url = reverse_lazy('catalog:catalog')
    permission_required = 'catalog.delete_product'

    def has_permission(self):
        product = self.get_object()
        user = self.request.user

        if product.owner == user:
            return True

        return super().has_permission()


class ContactsView(CategoriesMixin, TemplateView):
    template_name = 'catalog/contacts.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get("name")
        message = request.POST.get("message")
        return HttpResponse(f"Спасибо, {name}! Сообщение получено.")

catalog/templates/catalog/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Skystore</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

</head>
<body>

{% include 'catalog/header.html'%}

{% block description%}
{% endblock%}

<div class="container">

{% block content%}
{% endblock%}

{% include 'catalog/footer.html'%}
</div>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

catalog/templates/catalog/catalog.html
{% extends 'catalog/base.html'%}
{% load my_tags %}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Skystore - это отличный вариант хранения ваших плагинов и примеров кода, который вы бы хотели
        продать</p>
</div>
{% endblock%}

{% block content%}
<div class="row text-center">
    {% for product in products %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <img src="{{ product.image | media_filter }}"  class="card-img-top">
                <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                <h2>{{ product.price }} руб.</h2>
                <p>{{ product.description | truncatechars:100 }}</p>
                <a class="btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_detail' product.pk %}" role="button">Подробнее</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}

catalog/templates/catalog/contacts.html
{% extends 'catalog/base.html'%}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>
{% endblock%}

{% block content%}
<div class="row text-start">
    <div class="col-lg-9 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                <table class="table table-striped">
                    <tr>
                        <td class="w-25">Страна</td>
                        <td>USA</td>
                    </tr>
                    <tr>
                        <td class="w-25">ИНН</td>
                        <td>91-1144442</td>
                    </tr>
                    <tr>
                        <td class="w-25">Адрес</td>
                        <td>Redmond,WA,98052-6399</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-3 col-md-6 col-sm-12">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
            </div>
            <div class="card-body">
                <form method="post" action="" class="form-floating">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="name">Имя</label>
                        <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                    </div>
                    <div class="mb-3">
                        <label for="phone">Телефон</label>
                        <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                    </div>
                    <div class="mb-3">
                        <label for="message">Сообщение</label>
                        <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                    </div>
                    <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock%}

catalog/templates/catalog/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2025</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
            </ul>
        </div>
    </div>
</footer>

catalog/templates/catalog/header.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:catalog' %}">Каталог</a>
        <div class="btn-group">
            <button type="button" class="p-2 btn btn-outline-primary dropdown-toggle"
                    data-bs-toggle="dropdown" aria-expanded="false">
                Категории
            </button>
            <ul class="dropdown-menu">
                {% for category in categories %}
                <li>
                    <a class="dropdown-item"
                       href="{% url 'catalog:products_by_category' category.pk %}">
                        {{ category.name }}
                    </a>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:product_create' %}">Добавление товара</a>
        {% endif %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
        {% if user.is_authenticated %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:user_profile' user.pk %}">{{ user.email }}</a>
        <form method="post" action="{% url 'users:logout' %}" style="display: inline">
            {% csrf_token %}
            <button type="submit" class="p-2 btn btn-outline-primary">Выйти</button>
        </form>
        {% else %}
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:register' %}">Регистрация</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'users:login' %}">Вход</a>
        {% endif %}
    </nav>
</div>

catalog/templates/catalog/product_confirm_delete.html
{% extends 'catalog/base.html'%}
{% load my_tags %}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    <p class="lead">Удаление товара</p>
</div>
{% endblock%}

{% block content%}
<p>Вы действительно хотите удалить '{{ product.name }}'?</p>
<form method="post">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Удалить</button>
    <a href="{% url 'catalog:catalog' %}" class="btn btn-primary">Отменить</a>
</form>
{% endblock%}

catalog/templates/catalog/product_detail.html
{% extends 'catalog/base.html' %}
{% load my_tags %}

{% block content %}
<div class="col-3">
    <div class="card mb-4 box-shadow">
        <div class="card-body">
            <img src="{{ product.image | media_filter }}"  class="card-img-top">
            <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
            <h2>Цена: {{ product.price }} руб.</h2>
            <p>Категория: {{ product.category }}</p>
            <p>Описание: {{ product.description | truncatechars:100 }}</p>
            <p>Владелец: {{ product.owner }}</p>
            {% if 'catalog.can_unpublish_product' in perms or user == product.owner%}
            <a class="mb-2 btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
            {% endif %}
            <button type="button" class="mb-2 btn btn-lg btn-block btn-outline-primary">Купить</button>
            <a class="mb-2 btn btn-lg btn-block btn-outline-primary" href="{% url 'catalog:catalog' %}" role="button">Назад</a>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/catalog/product_form.html
{% extends 'catalog/base.html'%}
{% load my_tags %}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Skystore</h1>
    {% if object %}
    <p class="lead">Редактирование товара</p>
    {% else %}
    <p class="lead">Добавление товара</p>
    {% endif %}
</div>
{% endblock%}

{% block content%}
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    {% if object %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'catalog:catalog' %}" class="btn btn-primary">Отменить</a>
    {% if 'catalog.delete_product' in perms or user == product.owner%}
    <a href="{% url 'catalog:product_delete' product.pk %}" class="btn btn-danger">Удалить</a>
    {% endif %}
    {% else %}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'catalog:catalog' %}" class="btn btn-primary">Отменить</a>
    {% endif %}
</form>
{% endblock%}

catalog/templates/catalog/products_by_category.html
{% extends 'catalog/base.html'%}
{% load my_tags %}

{% block description%}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ category.name }}</h1>
    <p class="lead">{{ category.description }}</p>
</div>
{% endblock%}

{% block content%}
<div class="row text-center">
    {% for product in products_by_category %}
    <div class="col-3">
        <div class="card mb-4 box-shadow">
            <div class="card-body">
                {% if product.image %}
                <img src="{{ product.image | media_filter }}" class="card-img-top" alt="{{ product.name }}">
                {% endif %}
                <h1 class="card-title pricing-card-title">{{ product.name }}</h1>
                <h2>{{ product.price }} руб.</h2>
                <p>{{ product.description|truncatechars:100 }}</p>
                <p><small class="text-muted">{{ product.category.name }}</small></p>
                <a class="btn btn-lg btn-block btn-outline-primary" 
                   href="{% url 'catalog:product_detail' product.pk %}" 
                   role="button">Подробнее</a>
            </div>
        </div>
    </div>
    {% empty %}
    <div class="col-12">
        <div class="alert alert-info">
            {% if category %}
            В категории "{{ category.name }}" пока нет товаров.
            {% else %}
            Товаров пока нет.
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>
{% endblock%}